### ISSUE TITLE
점검 수정사항

### ISSUE THREAD

**Issue by myway00** [ECI-Equipment-module/eci-backend#147]
## 1) 문제상황 
- 거절 당하면 임시저장, 거부된 아이템 두개에 다 뜨게 된다 
 
![image](https://user-images.githubusercontent.com/76711238/174443250-279d8127-07db-4dfa-818e-20b50241a01e.png)

## 개선 방향

- 임시저장인데 거부된 것이라면 거부된 아이템에만 뜨게 한다.

**Comment by myway00** [comment]
해결완료 : ![image](https://user-images.githubusercontent.com/76711238/174445386-a32dd5f3-5a18-4e53-9083-30a01149a972.png)

**Comment by myway00** [comment]
Dashboard Service 예외 처리 진행해주기

**Comment by myway00** [comment]
프로젝트 서비스 dto 도 없으면 < (null)  이라면 > 빈 생성자로 초기화해서 객체를 돌려보내도록 리팩토링 진행

**Comment by myway00** [comment]
디자인 대쉬보드 info

**Comment by myway00** [comment]
item-candidates 줄때 revision 65 -> A로 변경하기

**Comment by myway00** [comment]
![image](https://user-images.githubusercontent.com/76711238/174524291-a86fa077-e2de-4904-950d-88c912288d59.png)

**Comment by myway00** [comment]
Complete 된 아이템에 대한 예외처리를 꼼꼼히 진행해줘야 한다.
- complete 된 BOM 아이템 DETAIL 들어가면 나는 에러
```
ext with path [] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6] with root cause

java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[na:na]
        at java.base/java.util.Objects.checkIndex(Objects.java:372) ~[na:na]
        at java.base/java.util.ArrayList.get(ArrayList.java:459) ~[na:na]
        at eci.server.config.guard.DesignGuard.isBeforeDesign(DesignGuard.java:200) ~[classes!/:na]
        at eci.server.config.guard.DesignGuard.reviewState(DesignGuard.java:170) ~[classes!/:na]
```
