### ISSUE TITLE
CATCHING ERRORS 🕷 & 변경 사항 반영 

### ISSUE THREAD

**Issue by myway00** [ECI-Equipment-module/eci-backend#181]
### BOM 로직 재점검 , 수정, 리팩토링, 오류 없게, 확실히!!!!!!!!!
- [x] 컴페어 봄 
   - [x] 컴패어봄 임시 저장 여부 판별해서 임시 저장 관계에서 봄 가져오냐 아니냐 판단
   - [x]  컴패어 봄 정렬 순서 반영 & 오류 고치기 

- [x] REVISE 시 BOM *** 
   - [x] 기존 ITEM  부모를 내 부모로 등록
   - [x] 기존 ITEM 의 
   - [x] 기존 ITEM의 DEV BOM 저장을 위해 문자열 필드 추가 (DEV-BOM)에

- [x] BOM 로직 확실히 정리 (임시 관계 등) 
   - [x]  임시 관계에서 보여줄 시 실제 관계로 보여주긴 해야하는데 그러고 있냐? 
   - [x] TEMP RELEATIONSHIP 이 DEV BOM으로 찐 저장될 때 얘의 TEMP RELATION 은 사라져야 함 

### EDITORS
- [x] Editors 추가 
   - [x] 일대다로 멤버 필드 editors 모든 곳에 추가 
   - [x]  editor set 메소드 생성)

### PROJECT
- [x] Project ** 
   - [x] 한 프로젝트는 여러 뉴아이템 가지기 가능 
   - [x]  라우트서 분리, 투두에서 분리
- [x] REVISE ITEM CREATE 시 기존 이미지 저장
   - [x] ITEM CREATE REQUEST에 이때는 기존 이미지 아이디 필드에 그 아이디 값 받아오도록 하기 

### REVISE ITEM 

- [x]  아이템 썸네일 건 
revise 로 아이템 생성 할 때 
thumbnailId 라는 추가적인 필드에다가 그 기존 이미지 아이디를 넣어서 주면 될 듯?? 
항상 기존이미지 아이디 넣어서 주되,
만약 thumbnail 이라는 키 값이 존재한다면 (사용자가 새 이미지를 넣었다면) 
그때는 그 새 이미지로 저장, 아니면 기존 아이디 값으로 이미지 저장! 
- [x] 아이템 REVISE 시 복제 문서 건 
   - DOCUMENT 랑 코드 똑같 
** 아이템 detail read 할 때 attahcment 빈 리스트거나 null 일 때도 잘 오나 500 안뜨나 검사 필요

### 복사& revise할 때

- duplicateTargetIds에다가 기존 문서 id를 보내주고
- 새로운 문서는 attachments : []에 보냈어 (file형식)
- [x]  코멘트, 태그도 보내줘야 한다. 그리고 순서도 맞춰줘야 한다.
- [x]  어태치 5개면, 기존거 2개, 새로 보내느거 3개가 있어
- [x]  리스트 하나에 5개씩 순서 맞춰서 보낸다
    - attachmentTag,attachmentComment

### 새로운 문제 -기존 edit과정에서의 문제

기존 코멘트, 태그를 수정할 경우

- 기존2개, 새로운거3개면
    - 새로운거 3개에 맞춰서 지금은 tag, comment를 보내고 있어.
- [x]  새로운 방식
    - 파일은 3개만 보낸다
    - 코멘트는 5개를 보낸다
    - 태그도 5개를 보낸다
- MEMBER - MODULE 이것들 

## Where Use !?
- [x] Where Use - 임시 저장 끝난 아이템마다 반영 

## Document
- [x] 거절당하면 rejected & 리스트에서 안 뜨네 하핫

## 영어로 데이터 이름 변경 
- [x] 영어로 변경하기 (데이터 주는 것)

## CR CO 
- [x] 차종 없어도 에러 안뜨게 하기 

## 아이템 임시 저장 
- [x] 이미지 업로드 안되는 문제

**Comment by myway00** [comment]
### EDITOR 작업 

```
CREATE TABLE new_item_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
new_item_id INT
);


CREATE TABLE project_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
project_id INT
);


CREATE TABLE design_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
design_id INT
);

CREATE TABLE cr_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
change_request_id INT
);

CREATE TABLE co_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
change_order_id INT
);

CREATE TABLE document_member(
id INT PRIMARY KEY AUTO_INCREMENT,
member_id INT,
document_id INT
);
```

**Comment by myway00** [comment]
Attachment comment & tag 수정 건

**Comment by myway00** [comment]
![image](https://user-images.githubusercontent.com/76711238/182790352-0683633c-9b8c-43b7-b70b-536ce1a8b24c.png)
새로운 refactor needed

**Comment by myway00** [comment]
```
         at eci.server.NewItemModule.dto.newItem.NewItemChildDto.lambda$toDtoList$1(NewItemChildDto.java:100) ~[classes!/:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.toDtoList(NewItemChildDto.java:110) ~[classes!/:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.lambda$toDtoList$1(NewItemChildDto.java:99) ~[classes!/:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.toDtoList(NewItemChildDto.java:110) ~[classes!/:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.lambda$toDtoList$1(NewItemChildDto.java:99) ~[classes!/:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.toDtoList(NewItemChildDto.java:110) ~[classes!/:na]
        at eci.server.NewItemModule.dto.newItem.NewItemChildDto.lambda$toDtoList$1(NewItemChildDto.java:99) ~[classes!/:na]
```

**Comment by myway00** [comment]
DOCUMENT - CREATE으로 잘못 설정된 것 REQUEST 로 변경

**Comment by myway00** [comment]
todo 띄울 때 type 같이 null 일 수도 있는 아이들은 (임시저장 때 선택 안 할 가능성이 높지) 꼭 예외 처리 해주자!

**Comment by myway00** [comment]
page customimpl 에서 기존 것들 뿐만 아니라 total (변수) / total page, element get  (메소드들) 도 override needed

```java
package eci.server.NewItemModule.entity.page;

import com.fasterxml.jackson.annotation.JsonGetter;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.lang.Nullable;

import java.util.List;

public class CustomPageImpl<T> extends PageImpl<T> {
    private final List<String> indexes;

    @Nullable
    private final List<Long> allResponsibleList;
    //새로운 인스턴스 변수 생성


    private final long total;

    @Override
    public long getTotalElements() {
        return total;
    }

    @Override
    public int getTotalPages() {
        return getSize() == 0 ? 1 : (int) Math.ceil((double) total / (double) getSize());
    }

    @Override
    public boolean hasNext() {
        return getNumber() + 1 < getTotalPages();
    }

    @Override
    public boolean isLast() {
        return !hasNext();
    }

    // 0811 : content 넘겨줄 때 이미 paging 이 레포지토리 단에서 완료된 채로 넘어와져야 한다. 레포지토리에서
    public CustomPageImpl(List<T> content, Pageable pageable, long total, List<String> indexes, @Nullable List<Long> allResponsibleList, long total1) {
        super(content, pageable, total);
        this.indexes = indexes;
        this.allResponsibleList = allResponsibleList;
        this.total = total1;
    }


    public CustomPageImpl(List<T> content, List<String> indexes, @Nullable List<Long> allResponsibleList, long total1) {
        super(content);
        this.indexes = indexes;
        this.allResponsibleList = allResponsibleList;
        System.out.println(total1 + " total 갱신 중이다아ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ");
        this.total = total1;
    }


    @JsonGetter(value = "contents")
    @Override
    public List getContent() {
        return super.getContent();
    }

    // 이 json getter 을 설정안해주면 json 반환에 아무것도 없음
    @JsonGetter(value = "indexes") //json 키 값에 보이게 되는 이름
    public List getPaging() {
        return indexes;
    }

    @JsonGetter(value = "all") //json 키 값에 보이게 되는 이름
    public List getIds() {
        return allResponsibleList;
    }

}

```

**Comment by myway00** [comment]
1) project complete 시점 건 
2) deadlock error debugging 건
